# -*- coding:utf-8 -*-
draw_url = ""
draw_key = ""
draw_model = ""
system_prompts = ""
chat_models = ""
debug = ""
triggers = ""
random_trigger = ""
AI_name = ""
ban_names = ""
ban_words = ""
root_ids = ""
send_debug = ""
speaker = ""
is_voice = ""
song = ""
singer = ""
